# Generated by Django 2.2.5 on 2020-09-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='attendant',
            new_name='booker',
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_tickets',
            field=models.PositiveSmallIntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='available_seats',
            field=models.PositiveIntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='seats',
            field=models.PositiveIntegerField(),
        ),
    ]
