# Generated by Django 2.2.5 on 2020-09-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200922_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='img',
            field=models.ImageField(blank=True, default='01.jpg', null=True, upload_to=''),
        ),
    ]
